### ISSUE TITLE
llama-2-70b-chat-hf on local 4  A100 GPUs

### ISSUE THREAD

**Issue by CinderZhang** [huggingface/blog#1384]
Would you mind how to load the model to 4 A100's on a Linux server? I have tried weeks but getting out of GPU memory errors all the time.
# the error message:
"
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 896.00 MiB (GPU 0; 39.43 GiB total capacity; 38.40 GiB already allocated; 135.75 MiB free; 38.41 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
"

# The code:
```
import os
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from torch.nn import DataParallel
import bitsandbytes as bnb


# Empty VRAM
torch.cuda.empty_cache()
import gc
gc.collect()
gc.collect()

model_name = "meta-llama/Llama-2-70b-chat-hf"
model = AutoModelForCausalLM.from_pretrained(model_name)

tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right" # Fix weird overflow issue with fp16 training
# Move the model to the default GPU
model.cuda()

# Wrap the model with DataParallel to utilize all GPUs
model = DataParallel(model, device_ids=[0, 1, 2, 3])

exit_commands = ["exit", "quit", "stop", "bye"]

while True:
    user_input = input("User: ")
    if user_input.lower() in exit_commands:
        print("Bot: Goodbye!")
        break
   
    # input_ids = tokenizer.encode(user_input, return_tensors="pt").to(device)
    input_ids = tokenizer.encode(user_input, return_tensors="pt").to('cuda')
    output = model.generate(input_ids, max_length=1048, do_sample=True, top_k=50, top_p=0.95, temperature=0.8, batch_size=16)

    generated_text = tokenizer.decode(output[0], skip_special_tokens=True)
    print("Bot:", generated_text)

```

**Comment by micolspitale93** [comment]
I got the same error. Have you found a solution to solve this?

**Comment by pcuenca** [comment]
Hello! You are loading all the weights to CPU in `float32` format, and then moving them to the GPUs. I'd recommend you use `float16` and load directly to the GPUs using `accelerate`:

```
pip install --upgrade accelerate transformers
```

```python
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto",
)
```

`device_map="auto"` is much faster because it loads to GPU directly, and distributes weights across all the GPUs available in your system. PyTorch's `cuda()` doesn't do this.

You can use less memory using quantized weights. You'll need the `bitsandbytes` library, and passing `load_in_8bit=True` or `load_in_4bit=True` to `from_pretrained`.

Please, check the blog post for more details: https://huggingface.co/blog/llama2#using-transformers
