### ISSUE TITLE
Arabic tokenizing  

### ISSUE THREAD

**Issue by MutazYounes** [huggingface/blog#41]
When I train the tokenizer on an Arabic data from https://wortschatz.uni-leipzig.de/en/download/arabic , I get this shape of Arabic letters. I tried changing the files encoding but nothing changed.

<img width="546" alt="Screen Shot 2020-07-14 at 11 21 41 PM" src="https://user-images.githubusercontent.com/49172046/87472620-e5865900-c628-11ea-858d-4796101615ea.png">

**Comment by n1t0** [comment]
This is totally expected when using a byte-level BPE tokenizer. As the name states, the tokens get encoded at the byte-level instead of the characters-level. But then when you decode everything looks "normal" again. Have a look here for a more in-depth explanation: https://github.com/huggingface/tokenizers/issues/203
